### ISSUE TITLE
希望前缀默认自动填写当前文件夹的名称

### ISSUE THREAD

**Issue by wisinfun** [panghujiajia/aliyundrive-batch-rename#1]
最好可以支持预先设定好格式，然后一键重命名，比如预先格式如：{{driveName}}.S01E{{number}}

**Comment by wisinfun** [comment]
另外感谢作者的分享，很方便~

**Comment by panghujiajia** [comment]
> 最好可以支持预先设定好格式，然后一键重命名，比如预先格式如：{{driveName}}.S01E{{number}}

谢谢，有用就好。
考虑到每个人使用场景不一样，对名字的格式也可能各不相同，所以自由度较高

**Comment by panghujiajia** [comment]
目前又有其他用户反馈要自动填写当前文件夹的名称，功能已更新
