### ISSUE TITLE
这个能不能在本地运行

### ISSUE THREAD

**Issue by jxz2333** [panghujiajia/aliyundrive-batch-rename#2]
这个可以改一下对已经下载下来的本地文件进行操作吗

**Comment by panghujiajia** [comment]
> 这个可以改一下对已经下载下来的本地文件进行操作吗

下载个utools 在里面安装个批量重命名插件就可以

**Comment by jxz2333** [comment]
> > 这个可以改一下对已经下载下来的本地文件进行操作吗
> 
> 下载个utools 在里面安装个批量重命名插件就可以

谢谢你 我自己用Python做了一个小工具。我的问题已经解决了，祝大佬生活愉快😃
